from typing import Protocol


class StorageDriverInterface(Protocol):
    def put(self, path: str, contents: bytes) -> None: ...

    def get(self, path: str) -> bytes: ...

    def delete(self, path: str) -> None: ...

    def exists(self, path: str) -> bool: ...

    def get_url(self, path: str) -> str: ...
