sonar.projectKey=backend-python
sonar.projectName=backend-python
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
# sonar.login is set via CI environment variable SONAR_TOKEN

# Ignore idiomatic FastAPI SessionLocal
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S1542
sonar.issue.ignore.multicriteria.e1.resourceKey=src/infra/database/db.py

# Ignore hardcoded dev env vars
sonar.issue.ignore.multicriteria.e2.ruleKey=secrets:S6736
sonar.issue.ignore.multicriteria.e2.resourceKey=src/shared/config/settings.py

# Ignore always-returning health router
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S3516
sonar.issue.ignore.multicriteria.e3.resourceKey=src/modules/health/router.py
