{
 "title": "Python Backend Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Requisições (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[30s])) by (method, path)"
    }
   ]
  },
  {
   "title": "Latência Média (Segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(http_request_duration_ms_sum[30s]) / rate(http_request_duration_ms_count[30s])) / 1000"
    }
   ]
  },
  {
   "title": "Requisições por Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[30s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident (RSS)" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual" }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "GC Collections (Por Minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(python_gc_collections_total[30s]) * 60",
     "legendFormat": "Gen {{generation}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "Abertos" },
    { "expr": "process_max_fds", "legendFormat": "Máximo" }
   ]
  },
  {
   "title": "GC Objects Collected (Por Minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[30s]) * 60",
     "legendFormat": "Gen {{generation}}"
    }
   ]
  },
  {
   "title": "Taxa de Exceções (Por Minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(exceptions_total[30s]) * 60",
     "legendFormat": "{{type}} (Status: {{status}})"
    }
   ]
  },
  {
   "title": "Queries no Banco (Por Minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(db_queries_total[30s]) * 60",
     "legendFormat": "Consultas Banco"
    }
   ]
  }
 ]
}