from collections.abc import Awaitable, Callable
from typing import Any, Protocol


class RabbitMQProviderInterface(Protocol):
    async def connect(self) -> None: ...

    async def declare_exchange(self, name: str, exchange_type: str = "direct", durable: bool = True): ...

    async def declare_queue(self, name: str, durable: bool = True, dlq: str | None = None, dlq_routing_key: str | None = None): ...

    async def bind(self, queue: str, exchange: str, routing_key: str = ""): ...

    async def setup_topology(self): ...

    async def publish(self, queue_name: str, message: Any, exchange: str | None = None, routing_key: str | None = None) -> None: ...

    async def subscribe(self, queue_name: str, callback: Callable[[Any], Awaitable[None]]) -> None: ...

    async def start_consumers(self): ...

    async def disconnect(self) -> None: ...
