from typing import Protocol


class RedisProviderInterface(Protocol):
    async def get(self, key: str): ...

    async def setex(self, key: str, time: int, value: str): ...

    async def incr(self, key: str): ...

    async def set_session(self, user_id: str, tokens: list, ttl: int = 7 * 24 * 3600): ...

    async def is_session_valid(self, user_id: str, token: str) -> bool: ...

    async def remove_token_from_session(self, user_id: str, token: str): ...

    async def invalidate_sessions(self, user_id: str): ...

    async def set_permissions(self, user_id: str, permissions: str, ttl: int = 60): ...

    async def get_permissions(self, user_id: str): ...

    async def invalidate_permissions(self, user_id: str): ...

    async def get_session_version(self, user_id: str): ...

    async def set_session_version(self, user_id: str, version: int, ttl: int = 3600): ...

    async def invalidate_session_version(self, user_id: str): ...

    async def is_locked(self, identifier: str) -> bool: ...

    async def increment_lockout(self, identifier: str): ...

    async def reset_lockout(self, identifier: str): ...
