"""add_soft_delete_to_feature

Revision ID: 32359e1b3300
Revises: 3850a17840e8
Create Date: 2026-05-02 16:53:11.551762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32359e1b3300'
down_revision: Union[str, Sequence[str], None] = '3850a17840e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('feature', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature', 'deleted_at')
    op.drop_column('feature', 'is_deleted')
    # ### end Alembic commands ###
