"""add_audit_and_parity_fix

Revision ID: 3850a17840e8
Revises: ec110af39822
Create Date: 2026-04-18 11:39:29.374115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3850a17840e8'
down_revision: Union[str, Sequence[str], None] = 'ec110af39822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    op.create_table('tb_audit',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('id_user', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.String(length=255), nullable=True),
    sa.Column('execute_type', sa.String(length=255), nullable=True),
    sa.Column('class', sa.String(length=255), nullable=True),
    sa.Column('function', sa.String(length=255), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('diff_value', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('tb_error_log',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('id_user', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    # op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('alembic_version',
    # sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    # )
    op.drop_table('tb_error_log', schema='audit')
    op.drop_table('tb_audit', schema='audit')
    # ### end Alembic commands ###
