"""auto_migration

Revision ID: aaa5f275344d
Revises: 32359e1b3300
Create Date: 2026-05-23 19:31:07.571030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa5f275344d'
down_revision: Union[str, Sequence[str], None] = '32359e1b3300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('alembic_version')
    op.add_column('product', sa.Column('id_user', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['id_user'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'id_user')
    # op.create_table('alembic_version',
    # sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    # )
    # ### end Alembic commands ###

